### ISSUE TITLE
Error: Invalid JSON RPC response

### ISSUE THREAD

**Issue by murilobast** [0xbitcoin/tokenpool#17]
When I try to run tokenpool on my vps I get this error:

```UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: "" ```

It looks like it isn't getting a valid response from mainnet on web3

**Comment by murilobast** [comment]
Ok, just got why I am getting this error.
I need an RPC server to connect but the question now is:
Can I use a public RPC like "https://api.myetherapi.com/eth" or do I need to setup a private one?

**Comment by roy33333** [comment]
I got the same errors.
Can anyone help me?
Here is message.
------------------------------------------------
Update Vardiff
checkBatchPaymentsStatus
(node:2583) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/home/user/tokenpool/node_modules/web3/node_modules/web3-core-helpers/src/errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (/home/user/tokenpool/node_modules/web3/node_modules/web3-providers-http/src/index.js:73:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/user/tokenpool/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/user/tokenpool/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpRequestError (/home/user/tokenpool/node_modules/xhr2/lib/xhr2.js:544:12)
    at ClientRequest.<anonymous> (/home/user/tokenpool/node_modules/xhr2/lib/xhr2.js:414:24)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:2583) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2583) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
done w for each 
listening on JSONRPC server localhost:8080
monitor mined solutions 
------------------------------------------------
