### ISSUE TITLE
installation smooth but website not showing up

### ISSUE THREAD

**Issue by goodthebest** [0xbitcoin/tokenpool#36]
@0xbitcoin hey guys

I've installed the pool, all seems well such but website isn't showing up rather getting this out put on the browser

# Cannot GET /

![image](https://user-images.githubusercontent.com/1715740/71997858-ff994600-3257-11ea-80ca-6a4e1ee10f58.png)

**Comment by admazzola** [comment]
You need to run 'npm run webpack' to build the web files and then 'npm run server' and then the website will show up on port 3000 like localhost:3000

**Comment by admazzola** [comment]
Also are you using Nginx for the web server?  If so, just use the config found in 'config/nginx/default'  :)  

Basically once you 'npm run webpack' youll see the static site built in  public/   and you can serve that however you want.   Its very simple.

**Comment by goodthebest** [comment]
> You need to run 'npm run webpack' to build the web files and then 'npm run server' and then the website will show up on port 3000 like localhost:3000

@admazzola 
I'm getting this error when I run **npm run webpack**

`TypeError: compilation.mainTemplate.applyPluginsWaterfall is not a function
    at /root/tokenpool/node_modules/html-webpack-plugin/lib/compiler.js:81:51
    at compile (/root/tokenpool/node_modules/webpack/lib/Compiler.js:343:11)
    at hooks.afterCompile.callAsync.err (/root/tokenpool/node_modules/webpack/lib/Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/tokenpool/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/tokenpool/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/root/tokenpool/node_modules/webpack/lib/Compiler.js:678:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/tokenpool/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/tokenpool/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/root/tokenpool/node_modules/webpack/lib/Compilation.js:1423:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/tokenpool/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/tokenpool/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/root/tokenpool/node_modules/webpack/lib/Compilation.js:1414:32)
    at _err0 (eval at create (/root/tokenpool/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at taskRunner.run (/root/tokenpool/node_modules/terser-webpack-plugin/dist/index.js:321:9)
    at TaskRunner.run (/root/tokenpool/node_modules/terser-webpack-plugin/dist/TaskRunner.js:48:7)
    at TerserPlugin.optimizeFn (/root/tokenpool/node_modules/terser-webpack-plugin/dist/index.js:227:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/tokenpool/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/root/tokenpool/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/root/tokenpool/node_modules/webpack/lib/Compilation.js:1409:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/tokenpool/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/tokenpool/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/root/tokenpool/node_modules/webpack/lib/Compilation.js:1405:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/tokenpool/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/tokenpool/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/root/tokenpool/node_modules/webpack/lib/Compilation.js:1342:27)
    at compilation.finish.err (/root/tokenpool/node_modules/webpack/lib/Compiler.js:675:18)
    at hooks.finishModules.callAsync.err (/root/tokenpool/node_modules/webpack/lib/Compilation.js:1261:4)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/tokenpool/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/root/tokenpool/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/root/tokenpool/node_modules/webpack/lib/Compilation.js:1253:28)
    at hooks.make.callAsync.err (/root/tokenpool/node_modules/webpack/lib/Compiler.js:672:17)
    at _err0 (eval at create (/root/tokenpool/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (/root/tokenpool/node_modules/webpack/lib/Compilation.js:1185:12)
    at processModuleDependencies.err (/root/tokenpool/node_modules/webpack/lib/Compilation.js:1097:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
`

**Comment by admazzola** [comment]
What in the world.... maybe you are using too new of a version of NodeJS or Webpack.  What versions you got?

**Comment by goodthebest** [comment]
nodejs v8.9.4
webpack showing empty

Perhaps I need to manually install can you please confirm which NodeJS version and webpack verson compatible?

**Comment by admazzola** [comment]
I use Node 8.12 and then I run 'npm install' and i actually have webpack 6.4.1 installed, i misspoke.  You can learn the version of your webpack with 'npm -v webpack' ! 

I just tested building the master branch with those versions and it works. Commit 6d874d8e7e0

**Comment by goodthebest** [comment]
thanks webpage issue solved

**Comment by admazzola** [comment]
Cool!  Find me in the discord if you need more help like with deploying the contracts for MintHelper or BatchedPayments (you can use Remix) or with help configuring the config files.

**Comment by goodthebest** [comment]
Cool man @admazzola will get in touch on Discord. again thanks and appreciate it.

**Comment by admazzola** [comment]
> thanks webpage issue resolved

Also I just realized that Babel was out of date.  That was probably your issue- if you were trying to update it , it was a mess.  I  updated it and you will see that in branch 'babel7'.  Hope that helps !

**Comment by goodthebest** [comment]
> > thanks webpage issue resolved
> 
> Also I just realized that Babel was out of date. That was probably your issue- if you were trying to update it , it was a mess. I updated it and you will see that in branch 'babel7'. Hope that helps !

Yes I had to manually install babel7 to make that work.

**Comment by goodthebest** [comment]
Another thing, in poool.config.js after enabling  **web3provider: "http://127.0.0.1:8545"** 

producing this error when I run the server

```
(node:29379) UnhandledPromiseRejectionWarning: Error: Couldn't decode uint256 from ABI: 0x
    at SolidityTypeUInt.formatOutputUInt [as _outputFormatter] (/root/tokenpool/node_modules/web3/node_modules/web3-eth-abi/src/formatters.js:174:15)
    at SolidityTypeUInt.SolidityType.decode (/root/tokenpool/node_modules/web3/node_modules/web3-eth-abi/src/type.js:252:17)
    at /root/tokenpool/node_modules/web3/node_modules/web3-eth-abi/src/index.js:327:49
    at Array.forEach (<anonymous>)
    at ABICoder.decodeParameters (/root/tokenpool/node_modules/web3/node_modules/web3-eth-abi/src/index.js:326:13)
    at Contract._decodeMethodReturn (/root/tokenpool/node_modules/web3/node_modules/web3-eth-contract/src/index.js:459:22)
    at Method.outputFormatter (/root/tokenpool/node_modules/web3/node_modules/web3-eth-contract/src/index.js:812:46)
    at Method.formatOutput (/root/tokenpool/node_modules/web3/node_modules/web3-core-method/src/index.js:163:54)
    at sendTxCallback (/root/tokenpool/node_modules/web3/node_modules/web3-core-method/src/index.js:475:33)
    at /root/tokenpool/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js:147:9
    at XMLHttpRequest.request.onreadystatechange (/root/tokenpool/node_modules/web3/node_modules/web3-providers-http/src/index.js:77:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/root/tokenpool/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/root/tokenpool/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/root/tokenpool/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/root/tokenpool/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:29379) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

```
